### ISSUE TITLE
Feature: parse rec: tag

### ISSUE THREAD

**Issue by Nadrieril** [sanpii/todo-txt#13]
A number of todo.txt applications use the `rec:` tag to denote recurring tasks (see e.g. http://topydo.org/#Recurrence). It is relatively easy to parse but I think it would be useful to have a `recurrence: Option<...>` field in the `Task` struct.

**Comment by sanpii** [comment]
I would like to keep the `Task` struct close to the todo.txt specification.

I already need this feature and I created an [extended task](https://github.com/sanpii/effitask/blob/master/src/tasks/task.rs). It’s maybe a good idea to create a `TaskExtra` with [common used features](https://docs.google.com/spreadsheets/d/11nqV2j8qc_O5SVsvkZ2JGZP98CABLQ6EwBxAQQi7Huc/edit#gid=0)?

**Comment by Nadrieril** [comment]
That would be quite nice

**Comment by sanpii** [comment]
Here the work in progress PR : https://github.com/sanpii/todo-txt/pull/15

Comments are welcome :smiley:
