### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by VladimirMarkelov** [sanpii/todo-txt#20]
Could you tell when you are going to create 2.0 release?

I'm asking because, at this moment, the instruction in the REAME (`todo-txt = "2.0"`) does not work. Due to the only `2.x` version is really `2.0-rc1` and `cargo` refuses to use it. So, one has to check what the latest `1.x` and then fix a project's Cargo.toml.

**Comment by sanpii** [comment]
You must use `2.0.0-rc1` version in Cargo.toml. Let me know if I break nothing in this release candidate and I can publish the stable version.

**Comment by VladimirMarkelov** [comment]
I have built with `rc-1`. At least basic stuff(list, add, done, delete) works, including correct setting "finish date".

**Comment by sanpii** [comment]
Published, thank you!
